### ISSUE TITLE
Add support for UVC Camera

### ISSUE THREAD

**Issue by ywdncn** [ujizin/Camposer#19]
**Is your feature request related to a problem? Please describe.**
The device I used didn't have a built-in camera, it connected to an external UVC Camera via USB.
Currently, there's no way to connect UVC Camera in Camposer.

**Describe the solution you'd like**
Add parameter when use CamSelector, it can be the VID/PID or a UsbDevice instance.

**Describe alternatives you've considered**
None.

**Are you willing to provide a PR?**
I'm a beginner programmer and this might be too difficult for me. But I'll try to help.

**Comment by ujizin** [comment]
Hey @ywdncn, thanks for opening the issue!

I've been searching about this in relation to CameraX because Camposer was built upon it, but AFAIK, UVC only supports `Camera2`. 😢 

It's possible that it may be supported in the future, considering that CameraX is built upon Camera2

You can find more information in the docs: https://source.android.com/docs/core/camera/external-usb-cameras.

Please feel free to share any research or information you come across regarding this topic

**Comment by ujizin** [comment]
> I found that on devices without a camera, adding the `USB_ACCESSORY_ATTACHED` permission in `AndroidManifest.xml` allows the UVC camera to be recognized as a Front/Back camera. This might be useful.

I couldn't find anything about `USB_ACCESSORY_ATTACHED` related to lens facing. Could you please fork the repository and test it on a sample project to see if it works?"
