### ISSUE TITLE
API 21: support

### ISSUE THREAD

**Issue by leonardorpaixao** [ujizin/Camposer#4]
API 21: support #4

**Comment by ujizin** [comment]
Hey @leonardorpaixao, first, thank you for the contribution 😄 

We've talked about changing the `minSdk` to 21 in this [discussion](https://github.com/ujizin/Camposer/discussions/3). 

Please feel free to change for `minSdk` 21 if you want in this PR, however, I won't launch a new release for now because I want to enforce that everything is ok with these news SDKs.

For now, if you want to use the library with sdk 22 I'd recommend to override the sdk in your android manifest.

```XML
<uses-sdk tools:overrideLibrary="com.ujizin.camposer"/>
```

**Comment by ujizin** [comment]
I got an error when I start recording video with SDK 21/22

```Kotlin

FATAL EXCEPTION: CameraX-video encoding thread
  Process: com.ujizin.sample, PID: 13274
  java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
	at androidx.camera.core.VideoCapture.videoEncode(VideoCapture.java:881)
	at androidx.camera.core.VideoCapture.lambda$startRecording$4$androidx-camera-core-VideoCapture(VideoCapture.java:511)
	at androidx.camera.core.VideoCapture$$ExternalSyntheticLambda4.run(D8$$SyntheticClass)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

I haven't seen this on the Google issue tracker 🤔, I'm working on figuring out that.

The other features look good to me, if you want to reproduce the bug, just start recording a video in the sample project.

**Comment by ujizin** [comment]
Hey @leonardorpaixao, I've seen this [Issue](https://github.com/android/camera-samples/issues/2#issuecomment-546812852) that looks to be very similar. 

I also tested some apps from [camera-samples](https://github.com/android/camera-samples) & [Camerax-demo](https://github.com/robertlevonyan/camerax-demo) and causes the same crash. 

So knowing that the crash is caused by cameraX and not for Camposer, I'll release a new version with `minSdk` 21 ASAP.

**ps:** I'm looking forward to using the new version 1.3.0 as soon as releasing stable, which updates the internal video capture features... it may be the possible fix for it.

Happy new year! 🎆

**Comment by leonardorpaixao** [comment]
What a good news! Thank you so much!

Happy new year @ujizin !! ✨
